version: '3.8'

services:
  # Backend Services
  backend:
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Management API
  management_api:
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=["https://your-domain.com"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Frontend UI
  ui:
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.your-domain.com
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # PostgreSQL Database
  postgres:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Redis Cache
  redis:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # NATS Message Broker
  nats:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Prometheus Monitoring
  prometheus:
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prod:/etc/prometheus
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Grafana Dashboard
  grafana:
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 