version: '3.8'

services:
  # Backend Services
  backend:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    command: uvicorn opmas.main:app --host 0.0.0.0 --port 8000 --reload

  # Management API
  management_api:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=["*"]
    volumes:
      - ./management_api:/app
    command: uvicorn opmas_mgmt_api.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend UI
  ui:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./ui:/app
      - /app/node_modules
    command: npm run dev

  # Prometheus Monitoring
  prometheus:
    volumes:
      - ./config/prometheus/dev:/etc/prometheus

  # Grafana Dashboard
  grafana:
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin 