from setuptools import find_packages, setup

setup(
    name="opmas",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.7",
    install_requires=[
        "nats-py>=2.10.0",
        "aiohttp==3.9.1",
        "pydantic==2.6.1",
        "pydantic-settings==2.1.0",
        "python-dotenv==1.0.1",
        "structlog==23.2.0",
        "prometheus-client==0.19.0",
        "sqlalchemy==2.0.25",
        "asyncpg==0.29.0",
        "pyyaml==6.0.1",
        "psutil==5.9.8",
        "fastapi>=0.110.0",
        "uvicorn[standard]>=0.29.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
            "pytest-mock>=3.10.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
        ],
    },
    author="OPMAS Team",
    author_email="opmas@example.com",
    description="OPMAS Core Package",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
