name: CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [test-core, test-management-api, test-ui]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Core
        uses: docker/build-push-action@v4
        with:
          context: ./core
          push: true
          tags: opmas/core:latest,opmas/core:${{ github.ref_name }}

      - name: Build and push Management API
        uses: docker/build-push-action@v4
        with:
          context: ./management_api
          push: true
          tags: opmas/management-api:latest,opmas/management-api:${{ github.ref_name }}

      - name: Build and push UI
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: true
          tags: opmas/ui:latest,opmas/ui:${{ github.ref_name }}

      - name: Deploy to Production
        if: startsWith(github.ref, 'refs/tags/')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/opmas
            docker-compose pull
            docker-compose up -d 